{% set name = "pyinfra" %}
{% set version = "3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyinfra-{{ version }}.tar.gz
  sha256: ea65f2048860dae6a7d86470d4a7ca67c9e2e82d671e781b849f1e5e163ad6db

build:
  noarch: python
  entry_points:
    - pyinfra=pyinfra_cli.__main__:execute_pyinfra
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - gevent >=1.5
    - paramiko >=2.7,<4
    - click >2
    - jinja2 >2,<4
    - python-dateutil >2,<3
    - setuptools
    - configparser
    - pywinrm
    - typeguard
    - distro >=1.6,<2
    - packaging >=16.1
    - graphlib-backport
    - typing-extensions
    - importlib-metadata

test:
  imports:
    - pyinfra
    - pyinfra_cli
  commands:
    - pip check
    - pyinfra --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pyinfra.com
  doc_url: https://docs.pyinfra.com/
  dev_url: https://github.com/Fizzadar/pyinfra
  summary: pyinfra automates/provisions/manages/deploys infrastructure.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
