{% set name = "pyinfra" %}
{% set version = "2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyinfra-{{ version }}.tar.gz
  sha256: 727fc45d0abd8cf3759b93706620ea6eb06f1517f7727210aa7b0d7131eb8914

build:
  noarch: python
  entry_points:
    - pyinfra=pyinfra_cli.__main__:execute_pyinfra
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >2
    - colorama <1
    - configparser
    - distro >=1.6,<2
    - gevent >=1.5
    - graphlib-backport
    - jinja2 >2,<4
    - paramiko >=2.7,<3
    - python >=3.6
    - python-dateutil >2,<3
    - pywinrm
    - setuptools

test:
  source_files:
    - tests
  imports:
    - pyinfra
    - pyinfra_cli
  commands:
    - pip check
    - pyinfra --help
    
    # Skip these ones, missing test resoruce files from sdist
    - rm tests/test_facts.py
    - rm tests/test_operations.py
    
    - pytest -vvv --capture=tee-sys -k "not test_user_op and not test_ansible not test_get_fact" tests
  requires:
    - pip
    - pytest

about:
  home: https://pyinfra.com
  doc_url: https://docs.pyinfra.com/
  dev_url: https://github.com/Fizzadar/pyinfra
  summary: pyinfra automates/provisions/manages/deploys infrastructure.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
