{% set name = "pyinfra" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyinfra-{{ version }}.tar.gz
  sha256: 5b57e2db71a7fc56b46dbf2d7a00232184244aabeb35e2ed8edfd9ac36b8bd8b

build:
  noarch: python
  entry_points:
    - pyinfra=pyinfra_cli.__main__:execute_pyinfra
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - gevent >=1.5
    - paramiko >=2.7,<4
    - click >2
    - jinja2 >2,<4
    - python-dateutil >2,<3
    - setuptools
    - configparser
    - pywinrm
    - typeguard
    - distro >=1.6,<2
    - packaging >=16.1
    - graphlib-backport
    - typing-extensions
    - importlib_metadata

test:
  imports:
    - pyinfra
    - pyinfra_cli
  commands:
    - pip check
    - pyinfra --help
  requires:
    - pip

about:
  home: https://pyinfra.com
  doc_url: https://docs.pyinfra.com/
  dev_url: https://github.com/Fizzadar/pyinfra
  summary: pyinfra automates/provisions/manages/deploys infrastructure.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
