{% set name = "pyinfra" %}
{% set version = "2.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyinfra-{{ version }}.tar.gz
  sha256: 9539486457175eff8e6da0ecd94445c374e032ed4ce117610f3e05d48e8e37c9

build:
  noarch: python
  entry_points:
    - pyinfra=pyinfra_cli.__main__:execute_pyinfra
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - gevent >=1.5
    - paramiko >=2.7,<4
    - click >2
    - jinja2 >2,<4
    - python-dateutil >2,<3
    - setuptools
    - configparser
    - pywinrm
    - distro >=1.6,<2
    - graphlib-backport

test:
  imports:
    - pyinfra
    - pyinfra_cli
  commands:
    - pip check
    - pyinfra --help
  requires:
    - pip

about:
  home: https://pyinfra.com
  doc_url: https://docs.pyinfra.com/
  dev_url: https://github.com/Fizzadar/pyinfra
  summary: pyinfra automates/provisions/manages/deploys infrastructure.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
