schema_version: 1

context:
  name: pyinfra
  version: "3.5.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyinfra-${{ version }}.tar.gz
  sha256: 9d8e928ae7fe43cd7d6d07a09654266ec1e4e15c3d0fd8411ae85d055eff6a0b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - pyinfra=pyinfra_cli.main:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - uv-dynamic-versioning
  run:
    - python >=${{ python_min }}
    - gevent >=1.5
    - paramiko >=2.7,<4
    - click >2
    - jinja2 >3,<4
    - python-dateutil >2,<3
    - typeguard >=4,<5
    - distro >=1.6,<2
    - packaging >=16.1
    - typing-extensions

tests:
  - python:
      imports:
        - pyinfra
        - pyinfra_cli
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - pyinfra --help

about:
  summary: pyinfra automates/provisions/manages/deploys infrastructure.
  license: MIT
  license_file: LICENSE.md
  homepage: https://pyinfra.com
  repository: https://github.com/Fizzadar/pyinfra
  documentation: https://docs.pyinfra.com/

extra:
  recipe-maintainers:
    - thewchan
